language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  after_success:
    - npm run semantic-release